[package]
name = "tantivy"
version = "0.19.2"
readme = "README.md"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "MIT"

[lib]
name = "tantivy"
crate-type = ["cdylib"]

[build-dependencies]
pyo3-build-config = { version = "0.18.0", registry = "github-quiq-sh" }

[dependencies]
chrono = { version = "0.4.23", registry = "github-quiq-sh" }
tantivy = { version = "0.19.2", registry = "github-quiq-sh" }
itertools = { version = "0.10.5", registry = "github-quiq-sh" }
futures = { version = "0.3.26", registry = "github-quiq-sh" }
serde_json = { version = "1.0.91", registry = "github-quiq-sh" }

[dependencies.pyo3]
version = "0.18.0"
features = ["extension-module"]
registry = "github-quiq-sh"